# Site settings
title: VatWeb &lt;CODE&gt; Blog
email: vincent@vatweb.fr
author: Vincent Audebert
description: "My blog which gives answers to random coding problems."
baseurl: ""
url: "http://vincentaudebert.github.io"
google_analytics: UA-2208857-7

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5

gems:
    - jekyll-redirect-from